version: '3'

services:
  db:
    image: postgres
  django_docker_cloud:
    image: iamgoku/django-docker-cloud:latest
    build: .
    container_name: django_docker_cloud
    command: ./scripts.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - IN_DOCKER=1
